#!/bin/sh
# ~/.xinitrc

#startup programs
mpd &
picom -f &
dwmblocks &
sxhkd &
redshift &
dunst &
setxkbmap -layout gb,us -variant intl,intl -option grp:alt_space_toggle
xwallpaper --output all --zoom $(find $HOME/img/wallpapers/ | shuf -n 1) &
xscreensaver -no-splash &
xmodmap ~/.config/X11/xmodmap &
mpDris2 &

#dwm loop
while true; do
	dwm > /dev/null 2>&1
done

# The WM or DE is the last thing to execute
exec dwm
