#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

NORMAL_COLOR=$(awk '$1 ~ "*.background" { print $2 }' .Xresources)
FOCUSED_COLOR=$(awk '$1 ~ "*.color4" { print $2 }' .Xresources)

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color	"$FOCUSED_COLOR"
bspc config normal_border_color		"$NORMAL_COLOR"

bspc rule -a Spotify desktop='^10'
bspc rule -a Steam desktop='^8' state=floating
bspc rule -a Lutris desktop='^8'
bspc rule -a TelegramDesktop desktop='^9'
bspc rule -a Zathura state=tiled
bspc rule -a MEGAsync state=floating
bspc rule -a Yad state=floating
