#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color	"#6272A4"
bspc config normal_border_color		"#44475A"

bspc rule -a firefox desktop='^2'
bspc rule -a Spotify desktop='^10'
bspc rule -a Steam desktop='^9'
bspc rule -a Lutris desktop='^9'
bspc rule -a TelegramDesktop desktop='^8'
bspc rule -a ICE-SSB-whatsapp desktop='^8'
bspc rule -a Zathura state=tiled
bspc rule -a MEGAsync state=floating
